KarYabiAsan/Models/jobsearcher.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace KarYabiAsan.Models
{
    public class jobsearcher
    {
        [Key]
        public int Id { get; set; }
        public string UserID { get; set; }
        public IdentityUser User { get; set; }
        public string Token { get; set; } = "";
        [Display(Name = "نام و نام خانوادگی")]
        public string Name { get; set; } = "";

        [Display(Name = "شماره همراه")]
        [Required(ErrorMessage = "شماره همراه را وارد کنید")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; } = "";
        [Display(Name = "آدرس ایمیل")]
        [Required(ErrorMessage = "آدرس ایمیل را وارد کنید")]
        [DataType(DataType.EmailAddress, ErrorMessage = "مقدار ورودی باید ایمیل باشد")]
        public string Email { get; set; }
        public string UinqCode { get; set; }
        [NotMapped]
        public string Password { get; set; }
        [NotMapped]
        public string OldPassword { get; set; }
    }
}

KarYabiAsan/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KarYabiAsan.Models;
using KarYabiAsan.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace KarYabiAsan.Controllers
{
    public class JobsController : Controller
    {
        private readonly KarYabiDBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public JobsController(KarYabiDBContext context, UserManager<IdentityUser> userManager)
        {

            _userManager = userManager;

            _context = context;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Job.ToListAsync());
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var IsPinned = _context.BadgedJobs.Where(p => p.UserId == user.Id).Select(p => p.JobId).ToList();
                var IsSended = _context.SendRezomes.Where(p => p.UserId == user.Id).Select(p => p.JobId).ToList();
                if (IsPinned.Contains(job.JobId))
                {
                    job.IsPinned = true;
                }
                if (IsSended.Contains(job.JobId))
                {
                    job.IsSend = true;
                }
            }

            Job_Category_ViewModel viewModel = new Job_Category_ViewModel();
            viewModel.JobCategory = await _context.JobCategories.ToListAsync();
            viewModel.Job = job;
            viewModel.Employer = await _context.Employer.Where(p => p.ID == job.Employer).FirstOrDefaultAsync();
            return View(viewModel);
        }

        public async Task<IActionResult> SendRezome(int JobID)
        {
            var UserJson = HttpContext.Session.GetString("User");
            jobsearcher User = new jobsearcher();
            if (!string.IsNullOrEmpty(UserJson))
            {
                User = Newtonsoft.Json.JsonConvert.DeserializeObject<jobsearcher>(UserJson);

            }
            var JobSearcheCode = _context.Rezomes.Where(p=>p.Id==User.Id).SingleOrDefault();
            if (JobSearcheCode==null)
            {
                ModelState.AddModelError("", "کارجویی با این مشخصات وجود ندارد");
                return RedirectToAction("Details", new { id = JobID });
            }
            var Rezome = _context.Rezomes.Where(p => p.JobSearcheCode == JobSearcheCode.JobSearcheCode).SingleOrDefault();
            if (Rezome==null)
            {
                ModelState.AddModelError("", "رزومه ای برای شما ثبت نشده");
                return RedirectToAction("Details", new { id = JobID });
            }
            var Rezome_Job = new Job_Rezome()
            {
                Job = JobID,
                Rezome = Rezome.UinqCode
            };
            _context.Job_Rezomes.Add(Rezome_Job);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details",new {id=JobID });
        }
       

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("JobId,Title,CateGory,State,City,Hamkari,MinimumWorkExperience,Salery,Decription,MyProperty,Gender,Educate,PayanKhedmat")] Job job)
        {
            if (id != job.JobId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.JobId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job = await _context.Job.FindAsync(id);
            _context.Job.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(int id)
        {
            return _context.Job.Any(e => e.JobId == id);
        }
    }
}

KarYabiAsan/Controllers/jobsearchersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KarYabiAsan.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using SelectPdf;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using KarYabiAsan.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace KarYabiAsan.Controllers
{
    [Authorize(Roles = "JobSearcher")]
    public class jobsearchersController : Controller
    {
        private readonly KarYabiDBContext _context;
        private IHostingEnvironment _env;
        private readonly Microsoft.AspNetCore.Mvc.ViewEngines.ICompositeViewEngine _viewEngine;
        private readonly SignInManager<IdentityUser> _SignManager;
        private readonly UserManager<IdentityUser> _userManager;

        public jobsearchersController(KarYabiDBContext context, IHostingEnvironment env, ICompositeViewEngine viewEngine, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> SignManager)
        {
            _context = context;
            _env = env;
            _viewEngine = viewEngine;
            _userManager = userManager;
            _SignManager = SignManager;
        }

        public async Task<IActionResult> LogIn()
        {
            //if (!User.IsInRole("JobSearcher"))
            //{
            //    ModelState.AddModelError("", "این بخش مربوط به کارجویان است ");
            //    await _SignManager.SignOutAsync();
            //    return View();
            //}
            return RedirectToAction(nameof(Details));
        }

        public async Task<IActionResult> Details(string Un = "", string Ps = "")
        {
            var user = await _userManager.GetUserAsync(User);
            if (!User.IsInRole("JobSearcher"))
            {
                await _SignManager.SignOutAsync();
                ModelState.AddModelError(string.Empty, "این بخش مربوط به کارجویان است");
                return RedirectToAction(nameof(LogIn));
            }
            var Userselected = _context.Jobsearchers.Include(p => p.User).Where(p => p.User == user).FirstOrDefault();
            if (Userselected == null)
            {
                return RedirectToAction(nameof(LogIn));
            }

            var jobsearcher = await _context.Jobsearchers
                .FirstOrDefaultAsync(m => m.UserID == user.Id);

            if (!user.PhoneNumberConfirmed)
            {
                return RedirectToAction(nameof(SendValidateCode), new { PhoneNumber = Userselected.Phone, UserId = user.Id, Un = Un, Ps = Ps });
            }
            ViewBag.LastForiJob = _context.Job.OrderBy(p => p.JobId).Take(4).ToList();

            ViewBag.SendRezome = _context.Job.Where(p => _context.SendRezomes.Where(x => x.UserId == user.Id).Select(x => x.JobId).Contains(p.JobId)).ToList();
            ViewBag.SendHamkari = _context.HamkariRequests.Where(p => p.RezomeId == Userselected.UinqCode).ToList();

            ViewBag.PinJob = _context.Job.Where(p => _context.BadgedJobs.Where(x => x.UserId == user.Id).Select(x => x.JobId).Contains(p.JobId)).ToList();
            return View(jobsearcher);
        }



        [HttpGet]
        public async Task<IActionResult> SendValidateCode(string PhoneNumber, string UserId, string Un = "", string ps = "")
        {
            var user = await _userManager.GetUserAsync(User);

            if (user.PhoneNumberConfirmed)
            {
                ModelState.AddModelError("Registered", "این شماره قبلا ثبت شده");
                return RedirectToAction(nameof(LogIn));
            }
            ViewBag.PhoneNumber = PhoneNumber;
            ViewBag.Un = Un;
            ViewBag.ps = ps;
            await SendVerifyCode(PhoneNumber, UserId);
            return View();
        }

        public async Task<IActionResult> VeriFyUserCode(string PhoneNumber, string Code, string Un = "", string ps = "")
        {
            var user = await _userManager.GetUserAsync(User);
            var isvalid = _context.UsersVerifies.Where(p => p.dateTime.Minute - DateTime.Now.Minute <= 2).ToList().Count() > 0 ? true : false;

            if (isvalid)
            {
                user.PhoneNumberConfirmed = true;
                await _userManager.UpdateAsync(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { Un = Un, Ps = ps });
            }
            else
            {
                await SendVerifyCode(PhoneNumber, user.Id);
                ViewBag.PhoneNumber = PhoneNumber;
                ModelState.AddModelError("ExpireCode", "این کد منقضی شده است");
                return RedirectToAction(nameof(Details), new { Un = Un, Ps = ps });
            }

        }
        public async Task<int> SendMessageAgain()
        {
            var user = await _userManager.GetUserAsync(User);
            var SendedMessages = _context.UsersVerifies.Where(p => p.dateTime > DateTime.Now.AddMinutes(-6) && p.PhoneNumber == user.Email).ToList();
            if (SendedMessages.Count < 5)
            {
                await SendVerifyCode(user.Email, user.Id);
                return 1;
            }
            else
            {
                return 0;
            }



        }
        public async Task SendVerifyCode(string PhoneNumber, string UserId)
        {
            Random random = new Random();
            int value = random.Next(1001, 9895);
            var Verify = new UsersVerifyMessage()
            {
                PhoneNumber = PhoneNumber,
                Code = value,
                dateTime = DateTime.Now
            };
            _context.UsersVerifies.Add(Verify);
            await _context.SaveChangesAsync();
            await SMS.KasBarg.SendCodeVerify(UserId, PhoneNumber, value + "");
        }

        // GET: jobsearchers/Details/5


        // GET: jobsearchers/Edit/5
        public async Task<IActionResult> Edit(jobsearcher jobsearcher)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("ExpireCode", "اطلاعات را به درستی وارد کنید");
                return RedirectToAction(nameof(Details));
            }

            _context.Jobsearchers.Update(jobsearcher);
            _context.SaveChanges();
            return RedirectToAction(nameof(Details));

        }



        public async Task<IActionResult> CreateRezomePDF()
        {

            var user = await _userManager.GetUserAsync(User);
            var Userselected = _context.Jobsearchers.Include(p => p.User).Where(p => p.User == user).FirstOrDefault();
            if (Userselected == null)
            {
                return RedirectToAction(nameof(LogIn));
            }

            var jobsearcher = await _context.Jobsearchers
                .FirstOrDefaultAsync(m => m.UserID == user.Id);

            if (!user.PhoneNumberConfirmed)
            {
                return RedirectToAction(nameof(SendValidateCode), new { PhoneNumber = Userselected.Phone, UserId = user.Id, Un = "", Ps = "" });
            }


            var Rezome = await RenderPartialViewToString("_PartialRezome", Userselected.UserID);
            SelectPdf.HtmlToPdf htmlToPdf = new SelectPdf.HtmlToPdf();
            PdfDocument pdfDocument = htmlToPdf.ConvertHtmlString(Rezome);
            byte[] pdf = pdfDocument.Save();
            pdfDocument.Close();
            return File(
                pdf,
                "application/pdf",
                "rezome.pdf"
                );
        }

        private async Task<string> RenderPartialViewToString(string viewName, string UserId)
        {
            var user = await _userManager.GetUserAsync(User);
            var Userselected = _context.Jobsearchers.Include(p => p.User).Where(p => p.User == user).FirstOrDefault();

            var rezom = await _context.Rezomes.Where(p => p.JobSearcheCode == "").SingleOrDefaultAsync();

            JobSearcherRezomeViewModel jobSearcherRezomeViewModel = new JobSearcherRezomeViewModel()
            {
                jobsearcher = Userselected,
                Rezome = rezom
            };
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.ActionDescriptor.ActionName;

            ViewData.Model = jobSearcherRezomeViewModel;

            using (var writer = new StringWriter())
            {
                ViewEngineResult viewResult =
                    _viewEngine.FindView(ControllerContext, viewName, false);

                ViewContext viewContext = new ViewContext(
                    ControllerContext,
                    viewResult.View,
                    ViewData,
                    TempData,
                    writer,
                    new Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelperOptions()
                );

                await viewResult.View.RenderAsync(viewContext);

                return writer.GetStringBuilder().ToString();
            }
        }

        [Authorize]
        public async Task<IActionResult> Exit()
        {
            //var Rezomes = _context.Rezomes.ToList();
            //foreach (var item in Rezomes)
            //{
            //    var user = new IdentityUser { UserName = item.PhoneNumber, Email = item.PhoneNumber };
            //    var result = await _userManager.CreateAsync(user, "123456");
            //    if (result.Succeeded)
            //    {
            //        _context.Jobsearchers.Add(new Models.jobsearcher() { UserID = user.Id, Email = "", Token = user.Id, Phone = item.PhoneNumber, Name = item.NameAndUserName, UinqCode = item.UinqCode });
            //        _context.SaveChanges();
            //    }
            //}

            await _SignManager.SignOutAsync();

KarYabiAsan/Views/jobsearchers/Delete.cshtml
@model KarYabiAsan.Models.jobsearcher

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>jobsearcher</h4>
    <hr />
    @*<dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>*@
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KarYabiAsan/Views/jobsearchers/Details.cshtml
@model KarYabiAsan.Models.jobsearcher

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="section-hero overlay inner-page bg-image pt-5 pb-0" style="background-image: url(../../images/hero_1.jpg)" );" id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <a href="">
                    @* todo *@
                    @* آدرس تصویر کارجو  *@
                    <img class="" src="" style="width: 100px;">
                </a>

                <h2 class="employer-det-co-title d-inline-block mr-2">@Model.Name </h2>
            </div>
            <div class="col-12 text-center karj">
                <a class="c-btn c-btn--secondary2 px-3" asp-controller="Rezomes" asp-action="CreateRezome">رزومه ساز</a>
                <a class="c-btn c-btn--secondary2 px-3" asp-controller="Rezomes" asp-action="ShowRezomeForUser">مشاهده رزومه</a>
                <a class="c-btn c-btn--secondary2 px-4" asp-controller="jobsearchers" asp-action="Exit">خروج</a>
            </div>
        </div>
    </div>
</section>


<section class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <div class="card p-4 mb-3">
                    <h5>تنظیمات حساب کاربری</h5>
                    <hr />
                    <form asp-controller="jobsearchers" asp-action="Edit">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="UserID" />
                        <input type="hidden" asp-for="Token" />
                        <input type="hidden" asp-for="UinqCode" />

                        <h5 class="mt-3">تغییر آدرس ایمیل</h5>

                        <div class="form-group">
                            <label class="">آدرس ایمیل</label>
                            <input type="text" asp-for="Email" value="@Model.Email" data-email="@Model.Email" class="form-control" placeholder="آدرس ایمیل خود را وارد کنید">
                            <span class="">این ایمیل فعلی شماست، میتوانید آن را تغییر دهید.</span>
                        </div>

                        <h5 class="mt-5">اطلاعات شخصی</h5>

                        <div class="form-group">
                            <label class="">نام و نام خانوادگی</label>
                            <input class="form-control" type="text" asp-for="Name" value="@Model.Name">
                        </div>

                        <div class="form-group">
                            <label class="">شماره تماس</label>
                            <input class="form-control" type="text" asp-for="Phone" value="@Model.Phone">
                        </div>

                        <div class="form-group karj text-left mb-3">
                            <input class="c-btn c-btn--secondary2 px-5" name="submit" type="submit" value="ذخیره کردن تغییرات">
                        </div>
                    </form>
                </div>
            </div>


            <div class="col-md-4 col-sm-12">

                <div class="p-2 mb-3">
                    <h5 class="text-center py-2">
                        شغل های نشان شده
                    </h5>
                    <div>
                        @foreach (var item in (ViewBag.PinJob as List<Job>))
                        {
                            <a class="card c-boxFeatured c-boxFeatured--rowBorder u-block mb-2" asp-controller="Jobs" asp-action="Details" asp-route-id="@item.JobId">
                                <span class="c-jobOverview c-jobOverview--primary">
                                    <span class="c-jobOverview__title c-jobOverview__title--premium u-paddingLeft25 u-inlineBlock">
                                        @item.Title
                                    </span>
                                    <ul class="c-jobOverview__info">
                                        <li class="c-jobOverview__infoItem">
                                            <span class="c-jobOverview__label">@item.CompanyName</span>
                                        </li>
                                        <li class="c-jobOverview__infoItem">
                                            <i class="fa fa-building"></i>
                                            <span class="c-jobOverview__label">@item.Address</span>
                                        </li>
                                        <li class="c-jobOverview__infoItem c-jobOverview__skills hidden-xs hidden-md">
                                            <i class="fa fa-wrench"></i>
                                            <span class="c-jobOverview__label">@item.Skills</span>
                                        </li>
                                    </ul>
                                </span>
                            </a>
                        }

                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">

                <div class="p-2 mb-3">
                    <h5 class="text-center py-2">
                        رزومه های ارسال شده
                    </h5>
                    <div>
                        @foreach (var item in (ViewBag.SendRezome as List<Job>))
                        {
                            <a class="card c-boxFeatured c-boxFeatured--rowBorder u-block mb-2" asp-controller="Jobs" asp-action="Details" asp-route-id="@item.JobId">
                                <span class="c-jobOverview c-jobOverview--primary karj">
                                    <span class="c-jobOverview__title c-jobOverview__title--premium u-paddingLeft25 u-inlineBlock">
                                        @item.Title
                                    </span>
                                    <ul class="c-jobOverview__info">
                                        <li class="c-jobOverview__infoItem">
                                            <span class="c-jobOverview__label">@item.CompanyName</span>
                                        </li>
                                        <li class="c-jobOverview__infoItem">
                                            <i class="fa fa-building"></i>
                                            <span class="c-jobOverview__label">@item.Address</span>
                                        </li>
                                        <li class="c-jobOverview__infoItem c-jobOverview__skills hidden-xs hidden-md">
                                            <i class="fa fa-wrench"></i>
                                            <span class="c-jobOverview__label">@item.Skills</span>
                                        </li>
                                    </ul>
                                </span>
                            </a>
                        }

                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">

                <div class="p-2 mb-3">
                    <h5 class="text-center py-2">
                        رزومه های ارسال شده
                    </h5>
                    <div>
                        @foreach (var item in (ViewBag.SendHamkari as List<HamkariRequest>))
                        {
                            <div class="card c-boxFeatured c-boxFeatured--rowBorder u-block mb-2">
                                <span class="c-jobOverview c-jobOverview--primary karj">
                                    <span class="c-jobOverview__title c-jobOverview__title--premium u-paddingLeft25 u-inlineBlock">
                                        @item.EmployerName
                                    </span>
                                    <ul class="c-jobOverview__info">
                                        <li class="c-jobOverview__infoItem c-jobOverview__skills hidden-xs hidden-md">
                                            <i class="fa fa-wrench"></i>
                                            <span class="c-jobOverview__label">@item.RequestDateShow</span>
                                        </li>
                                    </ul>
                                </span>
                                <span>
                                    <button class="btn btn-light border w-100 my-1" title="درخواست همکاری" onclick="ConfirmHamkariRequest(@item.Id)">
                                        @if (item.IsConfirmed)
                                        {
                                            <span class="fa fa-check-double" data-RequestHamkari="@item.Id"></span>
                                        }
                                        else
                                        {
                                            <span class="fa fa-handshake-o" data-RequestHamkari="@item.Id"></span>
                                        }
                                        <span style="font-size:13px;">قبول درخواست</span>
                                    </button>
                                </span>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{ 
<script>
    function ConfirmHamkariRequest(IdRquest) {
        $.ajax({
            type: "POST",
            url: "/jobsearchers/ConfirmHamkariRequest/",
            data: { IdRquest: IdRquest },
            dataType: "Json",
            success: function (result) {
                console.log(result);
                if (result == 1) {
                    $('span[data-RequestHamkari= ' + IdRquest + ']').removeClass('fa-handshake-o');
                    $('span[data-RequestHamkari= ' + IdRquest + ']').addClass('fa-check-double');
                }
                if (result == 0) {
                    $('span[data-RequestHamkari= ' + IdRquest + ']').removeClass('fa-check-double');
                    $('span[data-RequestHamkari= ' + IdRquest + ']').addClass('fa-handshake-o');
                }
                if (result == -1) {
                    $.toast({
                        heading: 'خطا',
                        text: 'برای درخواست همکاری باید ابتدا ورود داشته باشید.',
                        icon: 'error',
                        loader: true,
                        showHideTransition: 'fade'
                    });
                    return;
                }

            },
            error: function (req, status, error) {



            }
        });
    }
</script>
}

KarYabiAsan/Views/jobsearchers/LogIn.cshtml
@model KarYabiAsan.Models.jobsearcher
@{
    ViewData["Title"] = "LogIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="section-hero overlay inner-page bg-image" style="background-image: url(../../images/hero_1.jpg)" id="home-section">
    <div class="container">

        <h2 class="text-white mt-4">بخش کارجویان</h2>


    </div>
</section>
@*<section class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4 text-center c-boxWidget__header">ورود کارجو</h2>
                <form asp-controller="jobsearchers" asp-action="LogIn" class="p-5 card">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group mr-auto karj">
                        <input type="submit" value="ورود" class="c-btn c-btn--secondary2 px-5" />
                    </div>

                    <div>
                        <span>حساب کاربری ندارید؟</span>
                        <a asp-controller="jobsearchers" asp-action="Create" class="txtclr2 font-weight-bold">
                            ثبت نام کنید
                        </a>
                    </div>
                </form>
            </div>





        </div>
    </div>
</section>*@


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}